spring:
  application:
    name: user-service

secret:
  key: qK4dYg5j0nH+ZC3X9tqkPj8uQmE2rA7VbIwTzUuO1Hc=
  access-duration: 360000
  refresh-duration: 86400
  issuer: user-service

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
    try-it-out-enabled: true
  show-actuator: false
server:
  port: 8081
